NANOPB_RUNTIME_PATH = nanopb

INCLUDEPATH += $$NANOPB_RUNTIME_PATH
SOURCES += $$NANOPB_RUNTIME_PATH/pb_common.c \
           $$NANOPB_RUNTIME_PATH/pb_encode.c \
           $$NANOPB_RUNTIME_PATH/pb_decode.c

PROTODEF_PATH =  protodef
INCLUDEPATH += $$PROTODEF_PATH
INCLUDEPATH += $$PROTODEF_PATH/c

QMAKE_CFLAGS += -DPB_FIELD_16BIT
QMAKE_CXXFLAGS += -DPB_FIELD_16BIT

SOURCES += $$PROTODEF_PATH/c/messages.pb.c \
